import type { FastifyBaseLogger } from "fastify";
import { pool } from "./db.js";
import { listActiveSchedules, type PreventiveSchedule } from "./preventive-maintenance-repository.js";
import { createMaintenanceWorkOrder } from "./maintenance-work-orders-repository.js";

const EVAL_INTERVAL_MS = 60_000;

async function hasOpenWorkOrderForSchedule(scheduleId: string): Promise<boolean> {
  const result = await pool.query<{ exists: boolean }>(
    `SELECT EXISTS(
       SELECT 1 FROM maintenance_work_orders
       WHERE source_type = 'preventive_schedule' AND source_id = $1 AND status != 'closed'
     ) AS exists`,
    [scheduleId],
  );
  return result.rows[0]?.exists ?? false;
}

async function isDue(schedule: PreventiveSchedule): Promise<boolean> {
  const baseline = schedule.lastTriggeredAt ?? schedule.createdAt;

  if (schedule.triggerType === "calendar") {
    const result = await pool.query<{ days: number }>(
      `SELECT EXTRACT(EPOCH FROM (now() - $1::timestamptz)) / 86400 AS days`,
      [baseline],
    );
    return (result.rows[0]?.days ?? 0) >= schedule.intervalValue;
  }

  if (schedule.triggerType === "usage_hours") {
    const result = await pool.query<{ running_seconds: number }>(
      `WITH raw_status AS (
         SELECT payload->>'status' AS status, "timestamp" AS started_at,
                LEAD("timestamp") OVER (ORDER BY "timestamp") AS ended_at
         FROM events
         WHERE type = 'machine_status' AND machine_id = $1 AND "timestamp" >= $2::timestamptz
       )
       SELECT COALESCE(SUM(
         EXTRACT(EPOCH FROM (LEAST(COALESCE(ended_at, now()), now()) - GREATEST(started_at, $2::timestamptz)))
       ) FILTER (WHERE status = 'running'), 0) AS running_seconds
       FROM raw_status`,
      [schedule.machineId, baseline],
    );
    const runningHours = (result.rows[0]?.running_seconds ?? 0) / 3600;
    return runningHours >= schedule.intervalValue;
  }

  // part_count — minden legyártott darab számít (jó és selejt is), mert
  // ez fizikailag a gép ciklusszámát (kopását) reprezentálja.
  const result = await pool.query<{ count: string }>(
    `SELECT COUNT(*) FROM events WHERE type = 'production_count' AND machine_id = $1 AND "timestamp" >= $2::timestamptz`,
    [schedule.machineId, baseline],
  );
  return Number(result.rows[0]?.count ?? 0) >= schedule.intervalValue;
}

export function startPreventiveMaintenanceEvaluator(log: FastifyBaseLogger): void {
  const tick = async () => {
    try {
      const schedules = await listActiveSchedules();
      for (const schedule of schedules) {
        if (await hasOpenWorkOrderForSchedule(schedule.id)) continue;
        if (await isDue(schedule)) {
          await createMaintenanceWorkOrder({
            machineId: schedule.machineId,
            title: schedule.description,
            description: `Automatically generated by a preventive maintenance schedule (${schedule.triggerType}, threshold ${schedule.intervalValue}).`,
            sourceType: "preventive_schedule",
            sourceId: schedule.id,
          });
          log.warn(
            { scheduleId: schedule.id, machineId: schedule.machineId },
            "preventive maintenance work order created",
          );
        }
      }
    } catch (err) {
      log.error({ err }, "preventive maintenance evaluation tick failed");
    }
  };

  setInterval(() => void tick(), EVAL_INTERVAL_MS);
  void tick();
}